version: '3'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./todo-backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: todo_db
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build: ./todo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
